<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Details of each application that has been registered with the tool
        Schema::create('enrol_lti_app_registration', function (Blueprint $table) {
            $table->id('id');
            $table->string('name', 255)->comment('Common name to identify this platform to users');
            $table->text('platformid')->nullable()->comment('The issuer URL');
            $table->text('clientid')->nullable()->comment('The clientid string, generated by the platform when setting up the tool.');
            $table->string('uniqueid', 255)->comment('A unique local id, which can be used in the initiate login URI to provide {iss, clientid} uniqueness in the absence of the optional client_id claim.');
            $table->string('platformclienthash', 64)->nullable()->comment('SHA256 hash of the platformid (issuer) and clientid');
            $table->string('platformuniqueidhash', 64)->nullable()->comment('SHA256 hash of the platformid (issuer) and uniqueid');
            $table->text('authenticationrequesturl')->nullable()->comment('The authorisation endpoint of the platform');
            $table->text('jwksurl')->nullable()->comment('The JSON Web Key Set URL for the platform');
            $table->text('accesstokenurl')->nullable();
            $table->boolean('status')->default(0)->comment('Status of the registration, used to denote draft (incomplete) or active (complete)');
            $table->integer('timecreated');
            $table->integer('timemodified');

            // Unique Indexes
            $table->unique(['uniqueid'], 'uniqueid');
            $table->unique(['platformclienthash'], 'platformclienthash');
            $table->unique(['platformuniqueidhash'], 'platformuniqueidhash');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('enrol_lti_app_registration');
    }
};
