<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Stores the results of all the profiling runs
        Schema::create('profiling', function (Blueprint $table) {
            $table->id('id');
            $table->string('runid', 32)->comment('the unique id for this run (as generated by xhprof)');
            $table->string('url', 255)->comment('the url this profiling record is about (without wwwroot nor query params)');
            $table->text('data')->comment('the raw data gathered by xhprof');
            $table->integer('totalexecutiontime')->comment('time (in microseconds) spent by the run');
            $table->integer('totalcputime')->comment('time (in microseconds) spent by the CPU in this run');
            $table->integer('totalcalls')->comment('Total number of calls performed by the run');
            $table->integer('totalmemory')->comment('Total memory used byt the run');
            $table->tinyInteger('runreference')->default(0)->comment('Is this run a reference one');
            $table->string('runcomment', 255)->comment('Brief comment for this run');
            $table->integer('timecreated')->comment('unix timestap of the creation of this run');

            // Indexes
            $table->index(['url', 'runreference'], 'url_runreference_ix');
            $table->index(['timecreated', 'runreference'], 'timecreated_runreference_ix');

            // Unique Indexes
            $table->unique(['runid'], 'runid_uk');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('profiling');
    }
};
