@startuml
hide circle
skinparam linetype ortho

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Entity / Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    
    ' Entity styling (PlantUML treats entities similar to classes often, but explicit keywords align with class styling)
    ' If explicit entity styling is needed:
    EntityBackgroundColor white
    EntityBorderColor #4C5FD5
}


entity "**context**" as context {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  contextlevel : int NOT NULL DEFAULT '0' 
  instanceid : int NOT NULL DEFAULT '0' 
  path : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
  depth : tinyint NOT NULL DEFAULT '0' 
  locked : tinyint NOT NULL DEFAULT '0' COMMENT 'Whether this context and its children are locked' 
}

entity "**context_temp**" as context_temp {
  id : int NOT NULL COMMENT 'This id isn''t autonumeric/sequence. It''s the context->id' 
  path : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  depth : tinyint NOT NULL 
  locked : tinyint NOT NULL DEFAULT '0' COMMENT 'Whether this context and its children are locked' 
}

entity "**course**" as course {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  category : int NOT NULL DEFAULT '0' 
  sortorder : int NOT NULL DEFAULT '0' 
  fullname : varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL 
  shortname : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  idnumber : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  summary : text COLLATE utf8mb4_unicode_ci 
  summaryformat : tinyint NOT NULL DEFAULT '0' 
  format : varchar(21) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'topics' 
  showgrades : tinyint NOT NULL DEFAULT '1' 
  newsitems : smallint NOT NULL DEFAULT '1' 
  startdate : int NOT NULL DEFAULT '0' 
  enddate : int NOT NULL DEFAULT '0' 
  relativedatesmode : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether to let this course display course- or activity-related dates relative to the user''s enrolment date in this course.' 
  marker : int NOT NULL DEFAULT '0' 
  maxbytes : int NOT NULL DEFAULT '0' 
  legacyfiles : smallint NOT NULL DEFAULT '0' COMMENT 'course files are not necessary any more: 0 no legacy files 
  showreports : smallint NOT NULL DEFAULT '0' 
  visible : tinyint(1) NOT NULL DEFAULT '1' 
  visibleold : tinyint(1) NOT NULL DEFAULT '1' COMMENT 'the state of visible field when hiding parent category 
  downloadcontent : tinyint(1) DEFAULT NULL 
  groupmode : smallint NOT NULL DEFAULT '0' 
  groupmodeforce : smallint NOT NULL DEFAULT '0' 
  defaultgroupingid : int NOT NULL DEFAULT '0' COMMENT 'default grouping used in course modules 
  lang : varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Forced language for this course. Null or '''' means ''Do not force''. Otherwise a Moodle lang pack name like ''fr'' or ''en_us''.' 
  calendartype : varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL 
  theme : varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL 
  timecreated : int NOT NULL DEFAULT '0' 
  timemodified : int NOT NULL DEFAULT '0' 
  requested : tinyint(1) NOT NULL DEFAULT '0' 
  enablecompletion : tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 = allow use of ''completion'' progress-tracking on this course. 0 = disable completion tracking on this course.' 
  completionnotify : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Notify users when they complete this course' 
  cacherev : int NOT NULL DEFAULT '0' COMMENT 'Incrementing revision for validating the course content cache' 
  originalcourseid : bigint unsigned DEFAULT NULL COMMENT 'the id of the source course when a new course originates from a restore of another course on the same site.' (FK)
  showactivitydates : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether to display activity dates to user. 0 = do not display 
  showcompletionconditions : tinyint(1) DEFAULT NULL COMMENT 'Whether to display completion conditions to user. 0 = do not display 
  pdfexportfont : varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
}

entity "**course_categories**" as course_categories {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  idnumber : varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
  description : text COLLATE utf8mb4_unicode_ci 
  descriptionformat : tinyint NOT NULL DEFAULT '0' 
  parent : bigint unsigned NOT NULL DEFAULT '0' (FK)
  sortorder : int NOT NULL DEFAULT '0' 
  coursecount : int NOT NULL DEFAULT '0' 
  visible : tinyint(1) NOT NULL DEFAULT '1' 
  visibleold : tinyint(1) NOT NULL DEFAULT '1' COMMENT 'the state of visible field when hiding parent category 
  timemodified : int NOT NULL DEFAULT '0' 
  depth : int NOT NULL DEFAULT '0' 
  path : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  theme : varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Theme for the category' 
}

entity "**course_completion_aggr_methd**" as course_completion_aggr_methd {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  course : int NOT NULL DEFAULT '0' 
  criteriatype : int DEFAULT NULL COMMENT 'The criteria type we are aggregating 
  method : tinyint(1) NOT NULL DEFAULT '0' COMMENT '1 = all 
  value : decimal(10 
}

entity "**course_completion_crit_compl**" as course_completion_crit_compl {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : int NOT NULL DEFAULT '0' 
  course : int NOT NULL DEFAULT '0' 
  criteriaid : int NOT NULL DEFAULT '0' COMMENT 'Completion criteria this references' 
  gradefinal : decimal(10 
  unenroled : int DEFAULT NULL COMMENT 'Timestamp when the user was unenroled' 
  timecompleted : int DEFAULT NULL 
}

entity "**course_completion_criteria**" as course_completion_criteria {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  course : int NOT NULL DEFAULT '0' 
  criteriatype : int NOT NULL DEFAULT '0' COMMENT 'Type of criteria' 
  module : varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Type of module (if using module criteria type)' 
  moduleinstance : int DEFAULT NULL COMMENT 'Course module id (if using module criteria type)' 
  courseinstance : int DEFAULT NULL COMMENT 'Course instance id (if using course criteria type)' 
  enrolperiod : int DEFAULT NULL COMMENT 'Number of days after enrolment the course is completed (if using enrolperiod criteria type)' 
  timeend : int DEFAULT NULL COMMENT 'Timestamp of the date for course completion (if using date criteria type)' 
  gradepass : decimal(10 
  role : int DEFAULT NULL 
}

entity "**course_completion_defaults**" as course_completion_defaults {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  course : bigint unsigned NOT NULL (FK)
  module : bigint unsigned NOT NULL (FK)
  completion : tinyint(1) NOT NULL DEFAULT '0' 
  completionview : tinyint(1) NOT NULL DEFAULT '0' 
  completionusegrade : tinyint(1) NOT NULL DEFAULT '0' 
  completionpassgrade : tinyint(1) NOT NULL DEFAULT '0' 
  completionexpected : int NOT NULL DEFAULT '0' 
  customrules : text COLLATE utf8mb4_unicode_ci 
}

entity "**course_completions**" as course_completions {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : int NOT NULL DEFAULT '0' 
  course : int NOT NULL DEFAULT '0' 
  timeenrolled : int NOT NULL DEFAULT '0' 
  timestarted : int NOT NULL DEFAULT '0' 
  timecompleted : int DEFAULT NULL 
  reaggregate : int NOT NULL DEFAULT '0' 
}

entity "**course_format_options**" as course_format_options {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  courseid : bigint unsigned NOT NULL COMMENT 'Id of the course' (FK)
  format : varchar(21) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Format this option is for' 
  sectionid : int NOT NULL DEFAULT '0' COMMENT 'Null if this is a course option 
  name : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Name of the format option' 
  value : text COLLATE utf8mb4_unicode_ci COMMENT 'Value of the format option' 
}

entity "**course_modules**" as course_modules {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  course : int NOT NULL DEFAULT '0' 
  module : int NOT NULL DEFAULT '0' 
  instance : int NOT NULL DEFAULT '0' 
  section : int NOT NULL DEFAULT '0' 
  idnumber : varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'customizable idnumber' 
  added : int NOT NULL DEFAULT '0' 
  score : smallint NOT NULL DEFAULT '0' 
  indent : smallint NOT NULL DEFAULT '0' 
  visible : tinyint(1) NOT NULL DEFAULT '1' 
  visibleoncoursepage : tinyint(1) NOT NULL DEFAULT '1' COMMENT 'If stealth visibility is allowed for the course 
  visibleold : tinyint(1) NOT NULL DEFAULT '1' 
  groupmode : smallint NOT NULL DEFAULT '0' 
  groupingid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  completion : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Whether the completion-tracking facilities are enabled for this activity. 0 = not enabled (database default) 1 = manual tracking 
  completiongradeitemnumber : int DEFAULT NULL COMMENT 'Grade-item number used to track automatic completion 
  completionview : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Controls whether a page view is part of the automatic completion requirements for this activity. 0 = view not required 1 = view required' 
  completionexpected : int NOT NULL DEFAULT '0' COMMENT 'Date at which students are expected to complete this activity. This field is used when displaying student progress.' 
  completionpassgrade : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Enable completion check on passing grade.' 
  showdescription : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Some module types support a ''description'' which shows within the module pages. This option controls whether it also displays on the course main page. 0 = does not display (default) 
  availability : text COLLATE utf8mb4_unicode_ci COMMENT 'Availability restrictions for viewing this activity 
  deletioninprogress : tinyint(1) NOT NULL DEFAULT '0' 
  downloadcontent : tinyint(1) DEFAULT '1' COMMENT 'Whether the ability to download course module content is enabled for this activity' 
  lang : varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Forced language for this activity. Null or '''' means ''Do not force''. Otherwise a Moodle lang pack name like ''fr'' or ''en_us''.' 
}

entity "**course_modules_completion**" as course_modules_completion {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  coursemoduleid : int NOT NULL COMMENT 'Activity that has been completed (or not).' 
  userid : int NOT NULL COMMENT 'ID of user who has (or hasn''t) completed the activity.' 
  completionstate : tinyint(1) NOT NULL COMMENT 'Whether or not the user has completed the activity. Available states: 0 = not completed [if there''s no row in this table 
  overrideby : int DEFAULT NULL COMMENT 'Tracks whether this completion state has been set manually to override a previous state.' 
  timemodified : int NOT NULL COMMENT 'Time at which the completion state last changed.' 
}

entity "**course_modules_viewed**" as course_modules_viewed {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  coursemoduleid : int NOT NULL COMMENT 'Activity that has been viewed (or not).' 
  userid : int NOT NULL COMMENT 'ID of user who has (or hasn''t) viewed the activity.' 
  timecreated : int NOT NULL COMMENT 'Time at which the completion viewed created.' 
}

entity "**course_published**" as course_published {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  huburl : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'the url of the "registered on" hub' 
  courseid : bigint unsigned NOT NULL COMMENT 'the id of the published course' (FK)
  timepublished : int NOT NULL COMMENT 'The time when the publication occurred' 
  enrollable : tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 = enrollable 
  hubcourseid : int NOT NULL COMMENT 'the course id on the hub server' 
  status : tinyint(1) DEFAULT '0' COMMENT 'is the publication published or not' 
  timechecked : int DEFAULT NULL COMMENT 'the last time the status has been checked' 
}

entity "**course_request**" as course_request {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  fullname : varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL 
  shortname : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  summary : text COLLATE utf8mb4_unicode_ci NOT NULL 
  summaryformat : tinyint NOT NULL DEFAULT '0' 
  category : int NOT NULL DEFAULT '0' 
  reason : text COLLATE utf8mb4_unicode_ci NOT NULL 
  requester : int NOT NULL DEFAULT '0' 
  password : varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL 
}

entity "**course_sections**" as course_sections {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  course : int NOT NULL DEFAULT '0' 
  section : int NOT NULL DEFAULT '0' 
  name : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
  summary : text COLLATE utf8mb4_unicode_ci 
  summaryformat : tinyint NOT NULL DEFAULT '0' 
  sequence : text COLLATE utf8mb4_unicode_ci 
  visible : tinyint(1) NOT NULL DEFAULT '1' 
  availability : text COLLATE utf8mb4_unicode_ci COMMENT 'Availability restrictions for viewing this section 
  timemodified : int NOT NULL DEFAULT '0' COMMENT 'Time at which the course section was last changed.' 
}

entity "**groups**" as groups {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  courseid : bigint unsigned NOT NULL (FK)
  idnumber : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  name : varchar(254) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Short human readable unique name for the group.' 
  description : text COLLATE utf8mb4_unicode_ci 
  descriptionformat : tinyint NOT NULL DEFAULT '0' 
  enrolmentkey : varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
  picture : int NOT NULL DEFAULT '0' 
  visibility : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Visibility of group membership' 
  participation : tinyint(1) NOT NULL DEFAULT '1' COMMENT 'Can this group be selected when participating in activities?' 
  timecreated : int NOT NULL DEFAULT '0' 
  timemodified : int NOT NULL DEFAULT '0' 
}

entity "**groups_members**" as groups_members {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  groupid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  userid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  timeadded : int NOT NULL DEFAULT '0' 
  component : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Defines the Moodle component which added this group membership (e.g. ''auth_myplugin'') 
  itemid : int NOT NULL DEFAULT '0' COMMENT 'If the ''component'' field is set 
}

entity "**role**" as role {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Empty names are automatically localised' 
  shortname : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  description : text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Empty descriptions may be automatically localised' 
  sortorder : int NOT NULL DEFAULT '0' 
  archetype : varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Role archetype is used during install and role reset 
}

entity "**role_allow_assign**" as role_allow_assign {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  allowassign : bigint unsigned NOT NULL DEFAULT '0' (FK)
}

entity "**role_allow_override**" as role_allow_override {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  allowoverride : bigint unsigned NOT NULL DEFAULT '0' (FK)
}

entity "**role_allow_switch**" as role_allow_switch {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL COMMENT 'The role the user has.' (FK)
  allowswitch : bigint unsigned NOT NULL COMMENT 'The id of a role that the user is allowed to switch to as a result of having this role.' (FK)
}

entity "**role_allow_view**" as role_allow_view {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL COMMENT 'The role the user has.' (FK)
  allowview : bigint unsigned NOT NULL COMMENT 'The id of a role that the user is allowed to view to as a result of having this role.' (FK)
}

entity "**role_assignments**" as role_assignments {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  contextid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  userid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  timemodified : int NOT NULL DEFAULT '0' 
  modifierid : int NOT NULL DEFAULT '0' 
  component : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'plugin responsible responsible for role assignment 
  itemid : int NOT NULL DEFAULT '0' COMMENT 'Id of enrolment/auth instance responsible for this role assignment' 
  sortorder : int NOT NULL DEFAULT '0' 
}

entity "**role_capabilities**" as role_capabilities {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  contextid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  roleid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  capability : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL (FK)
  permission : int NOT NULL DEFAULT '0' 
  timemodified : int NOT NULL DEFAULT '0' 
  modifierid : bigint unsigned NOT NULL DEFAULT '0' (FK)
}

entity "**role_context_levels**" as role_context_levels {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL (FK)
  contextlevel : int NOT NULL 
}

entity "**role_names**" as role_names {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  roleid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  contextid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
}

entity "**user**" as user {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  auth : varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manual' 
  confirmed : tinyint(1) NOT NULL DEFAULT '0' 
  policyagreed : tinyint(1) NOT NULL DEFAULT '0' 
  deleted : tinyint(1) NOT NULL DEFAULT '0' 
  suspended : tinyint(1) NOT NULL DEFAULT '0' COMMENT 'suspended flag prevents users to log in' 
  mnethostid : int NOT NULL DEFAULT '0' 
  username : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  password : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  idnumber : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  firstname : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  lastname : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  email : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL 
  emailstop : tinyint(1) NOT NULL DEFAULT '0' 
  phone1 : varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL 
  phone2 : varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL 
  institution : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  department : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  address : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  city : varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL 
  country : varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL 
  lang : varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en' 
  calendartype : varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'gregorian' 
  theme : varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL 
  timezone : varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '99' 
  firstaccess : int NOT NULL DEFAULT '0' 
  lastaccess : int NOT NULL DEFAULT '0' 
  lastlogin : int NOT NULL DEFAULT '0' 
  currentlogin : int NOT NULL DEFAULT '0' 
  lastip : varchar(45) COLLATE utf8mb4_unicode_ci NOT NULL 
  secret : varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL 
  picture : int NOT NULL DEFAULT '0' COMMENT '0 means no image uploaded 
  description : text COLLATE utf8mb4_unicode_ci 
  descriptionformat : tinyint NOT NULL DEFAULT '1' 
  mailformat : tinyint(1) NOT NULL DEFAULT '1' 
  maildigest : tinyint(1) NOT NULL DEFAULT '0' 
  maildisplay : tinyint NOT NULL DEFAULT '2' 
  autosubscribe : tinyint(1) NOT NULL DEFAULT '1' 
  trackforums : tinyint(1) NOT NULL DEFAULT '0' 
  timecreated : int NOT NULL DEFAULT '0' 
  timemodified : int NOT NULL DEFAULT '0' 
  trustbitmask : int NOT NULL DEFAULT '0' 
  imagealt : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'alt tag for user uploaded image' 
  lastnamephonetic : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Last name phonetic' 
  firstnamephonetic : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'First name phonetic' 
  middlename : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Middle name' 
  alternatename : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Alternate name - Useful for three-name countries.' 
  moodlenetprofile : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Moodle.net profile information' 
}

entity "**user_devices**" as user_devices {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  appid : varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the app id 
  name : varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the device name 
  model : varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the device model 
  platform : varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the device platform 
  version : varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The device version 
  pushid : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'the device PUSH token/key/identifier/registration id' 
  uuid : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'The device vendor UUID' 
  publickey : text COLLATE utf8mb4_unicode_ci COMMENT 'The app generated public key' 
  timecreated : int NOT NULL 
  timemodified : int NOT NULL 
}

entity "**user_enrolments**" as user_enrolments {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  status : int NOT NULL DEFAULT '0' COMMENT '0..9 are system constants 
  enrolid : bigint unsigned NOT NULL (FK)
  userid : bigint unsigned NOT NULL (FK)
  timestart : int NOT NULL DEFAULT '0' 
  timeend : int NOT NULL DEFAULT '2147483647' 
  modifierid : bigint unsigned NOT NULL DEFAULT '0' (FK)
  timecreated : int NOT NULL DEFAULT '0' 
  timemodified : int NOT NULL DEFAULT '0' 
}

entity "**user_info_category**" as user_info_category {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Category name' 
  sortorder : int NOT NULL DEFAULT '0' COMMENT 'Display order' 
}

entity "**user_info_data**" as user_info_data {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : int NOT NULL DEFAULT '0' COMMENT 'id from the user table' 
  fieldid : int NOT NULL DEFAULT '0' COMMENT 'id from the field table' 
  data : text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Field data' 
  dataformat : tinyint NOT NULL DEFAULT '0' 
}

entity "**user_info_field**" as user_info_field {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  shortname : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'shortname' COMMENT 'short name for each field' 
  name : text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'field name' 
  datatype : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Type of data held in this field' 
  description : text COLLATE utf8mb4_unicode_ci COMMENT 'Description of field' 
  descriptionformat : tinyint NOT NULL DEFAULT '0' 
  categoryid : int NOT NULL DEFAULT '0' COMMENT 'id from category table' 
  sortorder : int NOT NULL DEFAULT '0' COMMENT 'order within the category' 
  required : tinyint NOT NULL DEFAULT '0' COMMENT 'Field required' 
  locked : tinyint NOT NULL DEFAULT '0' COMMENT 'Field locked' 
  visible : smallint NOT NULL DEFAULT '0' COMMENT 'Visibility: private 
  forceunique : tinyint NOT NULL DEFAULT '0' COMMENT 'should the field contain unique data' 
  signup : tinyint NOT NULL DEFAULT '0' COMMENT 'display field on signup page' 
  defaultdata : text COLLATE utf8mb4_unicode_ci COMMENT 'Default value for this field' 
  defaultdataformat : tinyint NOT NULL DEFAULT '0' 
  param1 : text COLLATE utf8mb4_unicode_ci COMMENT 'General parameter field' 
  param2 : text COLLATE utf8mb4_unicode_ci COMMENT 'General parameter field' 
  param3 : text COLLATE utf8mb4_unicode_ci COMMENT 'General parameter field' 
  param4 : text COLLATE utf8mb4_unicode_ci COMMENT 'General parameter field' 
  param5 : text COLLATE utf8mb4_unicode_ci COMMENT 'General parameter field' 
}

entity "**user_lastaccess**" as user_lastaccess {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : int NOT NULL DEFAULT '0' 
  courseid : int NOT NULL DEFAULT '0' 
  timeaccess : int NOT NULL DEFAULT '0' 
}

entity "**user_password_history**" as user_password_history {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : bigint unsigned NOT NULL (FK)
  hash : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  timecreated : int NOT NULL 
}

entity "**user_password_resets**" as user_password_resets {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : bigint unsigned NOT NULL COMMENT 'id of the user account which requester claimed to be' (FK)
  timerequested : int NOT NULL COMMENT 'The time that the user first requested this password reset' 
  timererequested : int NOT NULL DEFAULT '0' COMMENT 'The time the user re-requested the password reset.' 
  token : varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'secret set and emailed to user' 
}

entity "**user_preferences**" as user_preferences {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  userid : int NOT NULL DEFAULT '0' 
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  value : text COLLATE utf8mb4_unicode_ci NOT NULL 
}

entity "**user_private_key**" as user_private_key {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  script : varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'plugin 
  value : varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'private access key value' 
  userid : bigint unsigned NOT NULL COMMENT 'owner' (FK)
  instance : int DEFAULT NULL COMMENT 'optional instance id' 
  iprestriction : varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ip restriction' 
  validuntil : int DEFAULT NULL COMMENT 'timestampt - valid until data' 
  timecreated : int DEFAULT NULL COMMENT 'created timestamp' 
}

entity "**users**" as users {
  *id : bigint unsigned NOT NULL AUTO_INCREMENT 
  name : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  email : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  email_verified_at : timestamp NULL DEFAULT NULL 
  password : varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL 
  remember_token : varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL 
  created_at : timestamp NULL DEFAULT NULL 
  updated_at : timestamp NULL DEFAULT NULL 
}

entity "**capabilities**" as capabilities <<External>> {
  --
}

entity "**enrol**" as enrol <<External>> {
  --
}

entity "**groupings**" as groupings <<External>> {
  --
}

entity "**modules**" as modules <<External>> {
  --
}

course }|--|| course
course_categories }|--|| course_categories
course_completion_defaults }|--|| course
course_completion_defaults }|--|| modules
course_format_options }|--|| course
course_modules }|--|| groupings
course_published }|--|| course
groups }|--|| course
groups_members }|--|| groups
groups_members }|--|| users
role_allow_assign }|--|| role
role_allow_assign }|--|| role
role_allow_override }|--|| role
role_allow_override }|--|| role
role_allow_switch }|--|| role
role_allow_switch }|--|| role
role_allow_view }|--|| role
role_allow_view }|--|| role
role_assignments }|--|| context
role_assignments }|--|| role
role_assignments }|--|| users
role_capabilities }|--|| capabilities
role_capabilities }|--|| context
role_capabilities }|--|| users
role_capabilities }|--|| role
role_context_levels }|--|| role
role_names }|--|| context
role_names }|--|| role
user_devices }|--|| users
user_enrolments }|--|| enrol
user_enrolments }|--|| users
user_enrolments }|--|| users
user_password_history }|--|| users
user_password_resets }|--|| users
user_private_key }|--|| users
@enduml
