@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "choice" {
  +id : Integer
  +course : Integer
  +name : String
  +intro : String
  +introformat : Integer
  +publish : Integer
  +showresults : Integer
  +display : Integer
  +allowupdate : Integer
  +allowmultiple : Integer
  +showunanswered : Integer
  +includeinactive : Integer
  +limitanswers : Integer
  +timeopen : Integer
  +timeclose : Integer
  +showpreview : Integer
  +timemodified : Integer
  +completionsubmit : Integer
  +showavailable : Integer
  __
  +create()
  +update()
  +delete()
}

class "choice_answers" {
  +id : Integer
  +choiceid : Integer
  +userid : Integer
  +optionid : Integer
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

class "choice_options" {
  +id : Integer
  +choiceid : Integer
  +text : String
  +maxanswers : Integer
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

"choice_answers" "*" --> "1" "choice" : choiceid
"choice_answers" "*" --> "1" "choice_options" : optionid
"choice_options" "*" --> "1" "choice" : choiceid
@enduml
