@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "notifications" {
  +id : Integer
  +useridfrom : Integer
  +useridto : Integer
  +subject : String
  +fullmessage : String
  +fullmessageformat : Integer
  +fullmessagehtml : String
  +smallmessage : String
  +component : String
  +eventtype : String
  +contexturl : String
  +contexturlname : String
  +timeread : Integer
  +timecreated : Integer
  +customdata : String
  __
  +create()
  +update()
  +delete()
}

class "users" <<External>> {
}

"notifications" "*" --> "1" "users" : useridto
@enduml
