@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "url" {
  +id : Integer
  +course : Integer
  +name : String
  +intro : String
  +introformat : Integer
  +externalurl : String
  +display : Integer
  +displayoptions : String
  +parameters : String
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

@enduml
