@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "cache_filters" {
  +id : Integer
  +filter : String
  +version : Integer
  +md5key : String
  +rawtext : String
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

class "cache_flags" {
  +id : Integer
  +flagtype : String
  +name : String
  +timemodified : Integer
  +value : String
  +expiry : Integer
  __
  +create()
  +update()
  +delete()
}

class "cache_locks" {
  +key : String
  +owner : String
  +expiration : Integer
  __
  +create()
  +update()
  +delete()
}

@enduml
