@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "upgrade_log" {
  +id : Integer
  +type : Integer
  +plugin : String
  +version : String
  +targetversion : String
  +info : String
  +details : String
  +backtrace : String
  +userid : Integer
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

class "users" <<External>> {
}

"upgrade_log" "*" --> "1" "users" : userid
@enduml
