@startuml
hide circle

' Color Customization
skinparam {
    BackgroundColor white
    ArrowColor #4C5FD5
    
    ' Class Diagram specific
    ClassBackgroundColor white
    ClassBorderColor #4C5FD5
    ClassHeaderBackgroundColor #5AC8FA
    ClassAttributeFontColor black
    ClassStereotypeFontColor black
    
    ' Notes
    NoteBackgroundColor #FBBF24
    NoteBorderColor #FBBF24
}

skinparam classAttributeIconSize 0

class "rating" {
  +id : Integer
  +contextid : Integer
  +component : String
  +ratingarea : String
  +itemid : Integer
  +scaleid : Integer
  +rating : Integer
  +userid : Integer
  +timecreated : Integer
  +timemodified : Integer
  __
  +create()
  +update()
  +delete()
}

class "users" <<External>> {
}

class "context" <<External>> {
}

class "scale" <<External>> {
}

"rating" "*" --> "1" "context" : contextid
"rating" "*" --> "1" "scale" : scaleid
"rating" "*" --> "1" "users" : userid
@enduml
