@startuml
hide circle
skinparam classAttributeIconSize 0

class "modules" {
  +id : Integer
  +name : String
  +cron : Integer
  +lastcron : Integer
  +search : String
  +visible : Integer
  __
  +create()
  +update()
  +delete()
}

@enduml
